version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/JSONPublisher.war JSONPublisher.war
artifacts:
  files:
    - JSONPublisher.war
    - .ebextensions/**/*
    - base-directory: 'target/JSONPublisher'